### ISSUE TITLE
How use CUDA?

### ISSUE THREAD

**Issue by ukolovda** [zxcq544/russian_text_to_speech#12]
Hello! 

Readme say: "you can switch to cuda in NeuralSpeaker.py".

Please, say, how can I do it?

Thank you.

**Comment by ukolovda** [comment]
Changed code as:

```python
#        device = torch.device('cpu')
#        torch.set_num_threads(4)
        device = torch.device('cuda')
```

It seems works.

**Comment by zxcq544** [comment]
You are correct.  https://pytorch.org/docs/stable/notes/cuda.html
